"use client";

import React from "react";
import { motion } from "framer-motion";
import { headerContainerVariants, itemVariant } from "../utils/animations";

interface ImpactSectionProps {
  shouldReduceMotion: boolean;
}

const stats = [
  { value: "$62K+", label: "Generated by Menacity Clothing in its first 5 months" },
  { value: "150K+", label: "Site sessions driven to Menacity over 2 years" },
  { value: "60K+", label: "People in the Menacity community" },
  { value: "Millions", label: "Of records processed in PySpark and Elasticsearch pipelines" },
];

export default function ImpactSection({ shouldReduceMotion }: ImpactSectionProps) {
  const revealProps = shouldReduceMotion
    ? { initial: "visible", animate: "visible" }
    : { initial: "hidden", animate: "visible" };

  return (
    <div id="impact" className="w-full max-w-5xl mx-auto px-4 scroll-mt-24">
      <div className="text-center md:text-left mb-10">
        <span className="text-xs font-semibold tracking-widest uppercase text-[var(--olive-600)]">By The Numbers</span>
        <h2 className="text-2xl font-semibold text-stone-900 mt-2">Real Numbers From Real Projects</h2>
      </div>
      <motion.div
        {...revealProps}
        variants={headerContainerVariants}
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
      >
        {stats.map((stat) => (
          <motion.div key={stat.label} variants={itemVariant} className="glass rounded-2xl p-6 text-center flex flex-col items-center gap-2">
            <div className="text-3xl font-bold text-[var(--olive-700)]">{stat.value}</div>
            <div className="text-sm text-stone-600">{stat.label}</div>
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
}
